
version: '2.18'

services:
  mesto2:
    image: sysctl_image
    container_name: 'mesto2'
    privileged: true
    cap_add:
      - ALL    
    ports:
      - '3003:3003'
      - '3000:3000'
      - '3080:80'
      - '27017:27017'
    volumes:
      - '/home/alayna19/Pj/test_docker/:/home/test_docker'







